### ISSUE TITLE
Why LZF compression in one test?

### ISSUE THREAD

**Issue by ajelenak** [h5netcdf/h5netcdf#122]
Is there any particular reason to use LZF compression in this test:

https://github.com/h5netcdf/h5netcdf/blob/master/h5netcdf/tests/test_h5netcdf.py#L839-L851

Would something like gzip work as well?

**Comment by kmuehlbauer** [comment]
@ajelenak I do not see an immediate need that it has to be LZF. The best I can estimate from @shoyer's comment in the according commit is, that it used to be "an arbitrary" compressor. Back from the times where those were not implemented in netcdf.

**Comment by shoyer** [comment]
This is just a test for features that h5netcdf supports but not the official netcdf-C library, which require an explicit opt-in. If netcdf-C supports lzf now, we should no longer consider files using it on be "invalid netcdf files".

**Comment by shoyer** [comment]
In the context of alternative h5py implementations like h5pyd, there's no need for testing this. It's just something that happens to be supported by h5py.

**Comment by ajelenak** [comment]
Yes, that's why I was asking. h5pyd (more accurately, HDF Highly Scalable Data Service) does not currently have LZF compression. Thanks @kmuehlbauer, @shoyer for quickly replying.
