### ISSUE TITLE
decode_vlen_strings?? What are the advantages or disadvantages

### ISSUE THREAD

**Issue by hmaarrfk** [h5netcdf/h5netcdf#132]
https://github.com/h5netcdf/h5netcdf/blob/5196bc044c10549462bfa9634b0e4147eaeee4dd/h5netcdf/core.py#L937

The warnings reads:
> FutureWarning: String decoding changed with h5py >= 3.0. See https://docs.h5py.org/en/latest/strings.html for more details. Currently backwards compatibility with h5py < 3.0 is kept by decoding vlen strings per default. This will change in future versions for consistency with h5py >= 3.0. To silence this warning set kwarg ``decode_vlen_strings=False``. Setting ``decode_vlen_strings=True`` forces vlen string decoding.

The warning is rather unclear about what it means for the end user application?

I read through: https://github.com/h5netcdf/h5netcdf/issues/81 but I'm still a little confused.

Will my data be changed? Will I stop being able to read old data? Will new data be corrupt if i open it with netcdf4? It would be good to have an example of both.

To be honest, it would be good to have a little example showing how the different setting is interpretted once we move the dataset out of h5netcdf, either to h5py or to netcdf4.

**Comment by kmuehlbauer** [comment]
Bottom line:

`decode_vlen_strings = True` -> vlen strings are read as `str`
`decode_vlen_strings = False` -> vlen strings are read as `bytes`

**Comment by hmaarrfk** [comment]
Thank you very much for the fast response.

Maybe I am interpreting things badly, but
```python
import h5netcdf
import h5py
a = h5netcdf.File(f"test_my_{decode_vlen_strings}.nc", "w")
a.dimensions = {"x": 5}
v = a.create_variable("var_len_str", ("x"), dtype=h5py.special_dtype(vlen=str))
v[0] = "hello"
v[1] = "goodbye"
del v
a.close()

decode_vlen_strings = False
with h5netcdf.File(f"test_my_{decode_vlen_strings}.nc", "r", decode_vlen_strings=decode_vlen_strings) as a:
    v = a["var_len_str"]
    print(f"{decode_vlen_strings=:}")
    print(v.__class__)
    print(v[0])
    print(v[0].__class__)
    print(v[1])
    print(v[1].__class__)
    
decode_vlen_strings = True
with h5netcdf.File(f"test_my_{decode_vlen_strings}.nc", "r", decode_vlen_strings=decode_vlen_strings) as a:
    v = a["var_len_str"]
    print(f"{decode_vlen_strings=:}")
    print(v.__class__)
    print(v[0])
    print(v[0].__class__)
    print(v[1])
    print(v[1].__class__)
```

The output seems the same

```python
decode_vlen_strings=False
<class 'h5netcdf.core.Variable'>
b'hello'
<class 'bytes'>
b'goodbye'
<class 'bytes'>
decode_vlen_strings=True
<class 'h5netcdf.core.Variable'>
b'hello'
<class 'bytes'>
b'goodbye'
<class 'bytes'>

```

**Comment by hmaarrfk** [comment]
Sorry for the previous post. I had a hacked version of `h5netcdf` when creating it.

The example is clear:

```
import h5netcdf
import h5py
a = h5netcdf.File(f"test.nc", "w")
a.dimensions = {"x": 5}
v = a.create_variable("var_len_str", ("x"), dtype=h5py.special_dtype(vlen=str))
v[0] = "hello"
v[1] = "goodbye"
del v
a.close()
```
```
decode_vlen_strings = False
with h5netcdf.File(f"test_my_{decode_vlen_strings}.nc", "r", decode_vlen_strings=decode_vlen_strings) as a:
    v = a["var_len_str"]
    print(f"{decode_vlen_strings=:}")
    print(v[0])
    print(v[1])
    print(v[1].__class__)
    
decode_vlen_strings = True
with h5netcdf.File(f"test_my_{decode_vlen_strings}.nc", "r", decode_vlen_strings=decode_vlen_strings) as a:
    v = a["var_len_str"]
    print(f"{decode_vlen_strings=:}")
    print(v[0])
    print(v[1])
    print(v[1].__class__)
```

**Comment by kmuehlbauer** [comment]
The output:

```
decode_vlen_strings=False
b'hello'
b'goodbye'
<class 'bytes'>
decode_vlen_strings=True
hello
goodbye
<class 'str'>
```

**Comment by hmaarrfk** [comment]
Ah sorry, I didn't copy it.

**Comment by hmaarrfk** [comment]
Thank you! So now the question is:
what should xarray do to silence this warning ;)

**Comment by kmuehlbauer** [comment]
Good question. xarray is creating a new file or overwriting variables in an existing file with `to_netcdf`. It can just forward that keyword when writing files, but that seems like a hack.

**Comment by hmaarrfk** [comment]
I think the warning was being issued from my library (i'm appending to a netcdf file, but not entirely ready to make a PR to xarray with that feature)

Thank you again for the huge amount of context you provided.
