### ISSUE TITLE
Tracking issue for upstream order_tracking bug

### ISSUE THREAD

**Issue by hmaarrfk** [h5netcdf/h5netcdf#143]
xref: https://github.com/h5py/h5py/issues/1385

It does somewhat seem like it is a bug in hdf5. I wonder if we can recreate it in netcdf4 and get them involved too!

**Comment by kmuehlbauer** [comment]
I've come up with a workaround which also has the nice advantage to be a bit more performant when creating millions of attributes ;-)

https://github.com/h5py/h5py/pull/2042

FYI: @paugier

**Comment by kmuehlbauer** [comment]
I've tested that patch a bit. So the `track_order` problem is avoided then. 

But a major pain point is, that every change of an attribute would delete and recreate it. With `track_order=True` this would move the changed attribute to the back of the list.

I think we need to fix this either in `h5py` (allowing to `modify` existing attributes with same dtype) or in `h5netcdf`. It seems, that netCDF4 keeps this order regardless of an attribute has changed value and/or type.

**Comment by hmaarrfk** [comment]
Does netCDF4 suffer from the same issue? or no because they don't rename variable like h5py does?

**Comment by kmuehlbauer** [comment]
Yes, netCDF4 suffers from the same issue. At least first tests suggest this.

**Comment by kmuehlbauer** [comment]
```python
import netCDF4
with netCDF4.Dataset("test.nc", mode="w") as nc:
    g = nc.createGroup("grp0")
    g.test12 = 12
    g.test0 = 0
    g.test1 = 1
    g.test2 = 2
    g.test3 = 3
    g.test4 = 4
    g.test5 = 5
    g.test6 = 6
    g.test7 = 7
    g.test8 = 8
    g.test9 = 9
    g.test10 = 10
    g.test11 = 11

with netCDF4.Dataset("test.nc", mode="r") as nc:
    print(nc["grp0"])

with netCDF4.Dataset("test.nc", mode="a") as nc:
    g = nc["grp0"]
    g.test8 = 4
    g.test9 = "3"
    g.test1 = 42.
    
with netCDF4.Dataset("test.nc", mode="r") as nc:
    print(nc["grp0"])
```

```python
<class 'netCDF4._netCDF4.Group'>
group /grp0:
    test12: 12
    test0: 0
    test1: 1
    test2: 2
    test3: 3
    test4: 4
    test5: 5
    test6: 6
    test7: 7
    test8: 8
    test9: 9
    test10: 10
    test11: 11
    dimensions(sizes): 
    variables(dimensions): 
    groups: 
<class 'netCDF4._netCDF4.Group'>
group /grp0:
    test12: 12
    test0: 0
    test2: 2
    test3: 3
    test4: 4
    test5: 5
    test6: 6
    test7: 7
    test8: 4
    test10: 10
    test11: 11
    test1: 42.0
    test9: 3
    dimensions(sizes): 
    variables(dimensions): 
    groups: 
```

**Comment by kmuehlbauer** [comment]
@hmaarrfk So, only if the data type is the same, netCDF4 just modifies the entry. `h5py` recreates in any case atm. So we would need to fix either in `h5py` or `h5netcdf`.

But I'm wondering why `test9` is listed after `test1` although it has been changed the other way round.

**Comment by kmuehlbauer** [comment]
> But I'm wondering why `test9` is listed after `test1` although it has been changed the other way round.

Further tests indicate, that this might be connected with [attr_phase_change](https://api.h5py.org/h5p.html?highlight=phase_change#h5py.h5p.PropOCID.set_attr_phase_change) setting.

It looks like attributes in compact storage are somehow handled differently from attributes in dense storage.

**Comment by kmuehlbauer** [comment]
`netcdf-c` deletes the attribute in the hdf5 file (`H5Adelete`) when renaming. It keeps the renamed attribute in internal netcdf-c cache, so it get's written to the file in consequence. The data will be written most likely before the objects go out of scope or on file close/flush.

https://github.com/Unidata/netcdf-c/blob/e7e2f40188a35011feb25a13b4a129b495a28043/libhdf5/hdf5attr.c#L153-L245

Similar will be true, when overwriting an attribute. That's most likely the reason why `netcdf-python`/`netcdf-c` does not suffer from this weird rename/create bug as they actually do not rename anything.

**Comment by kmuehlbauer** [comment]
@hmaarrfk with h5py 3.7.0 out our tracking test:

https://github.com/h5netcdf/h5netcdf/blob/9c0269fa78286dd5a3547a040dd3b6c8902e9a68/h5netcdf/tests/test_h5netcdf.py#L1597-L1614

isn't failing any more. We would need to reevaluate the situation.

**Comment by kmuehlbauer** [comment]
see https://github.com/h5netcdf/h5netcdf/pull/173

**Comment by kmuehlbauer** [comment]
Looks like we can reinstate `track_feature=True` as default.
