### ISSUE TITLE
setuptools_scm replaces version with local git reference

### ISSUE THREAD

**Issue by drew-parsons** [h5netcdf/h5netcdf#156]
#### What happened:

Trying to build h5netcdf 0.14.1 from source extracted from the h5netcdf pypi source tarball, but stored locally in a git repo, the version file gets corrupted to a random reference derived from my local git repo.

The file corruption is triggered when running the clean rule with setup.py. It must be a consequence of the setuptools_scm change to setup.py introduced in PR #146  (commit 5a29b6c)

For instance, running from the source dir which also happens to contain a .git folder,
```
/build/python-h5netcdf$ cat h5netcdf/_version.py 
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.14.1'
version_tuple = (0, 14, 1)

/build/python-h5netcdf$ python3 setup.py clean
running clean

/build/python-h5netcdf$ cat h5netcdf/_version.py 
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.13.0.dev3+g26a0104'
version_tuple = (0, 13, 0, 'dev3', 'g26a0104')
```

The last local git commit (which loaded the h5netcdf source into the git repo) was 26a0104064, giving a clue where the corrupted version reference came from.

It looks like the new PR #146 arrangement using setuptools_scm is not robust.   _version.py gets overwritten by local git conditions.

If setup.py is no longer supposed to be used to build the package, since there is a pyproject.toml file, then maybe setup.py should be removed altgether? (the new [PEP 518](https://www.python.org/dev/peps/pep-0518/) regime)

#### What you expected to happen:

The version should remain unchanged as 0.14.1

#### Anything else we need to know?:

The h5netcdf is stored in a git repo for debian package, https://salsa.debian.org/science-team/python-h5netcdf
The pypi source tarball is used since usually it represents the source as intended for installation and usage. The source tarball provided by github is sometimes discrepant from the release tarball.

#### Version

0.14.1

**Comment by drew-parsons** [comment]
It's the `tool.setuptools_scm` entry in pyproject.toml that's causing the version file corruption.

**Comment by kmuehlbauer** [comment]
@drew-parsons Thanks for bringing this to attention. I'll have a look into this. If you have any idea how to resolve this, please let us know.

**Comment by kmuehlbauer** [comment]
From all what I could gather in short time, the suggestion of setuptools_scm devs is to use environment variable `SETUPTOOLS_SCM_PRETEND_VERSION` end provide the wanted version there during the build. That was especially recommended for debian-packaging, see https://github.com/pypa/setuptools_scm/issues/361.

This works flawless locally:

```
$ cat h5netcdf/_version.py
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '1.14.1'
version_tuple = (1, 14, 1)

$ SETUPTOOLS_SCM_PRETEND_VERSION=1.14.1 python setup.py clean
running clean

$ cat h5netcdf/_version.py
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '1.14.1'
version_tuple = (1, 14, 1)
```

**Comment by kmuehlbauer** [comment]
XRef: https://www.mail-archive.com/python-modules-team@lists.alioth.debian.org/msg31355.html

**Comment by drew-parsons** [comment]
Thanks for checking on it.  I'll look into what our build tools are doing with SETUPTOOLS_SCM_PRETEND_VERSION

**Comment by kmuehlbauer** [comment]
@drew-parsons Did you come any further with this? ``h5netcdf`` is approaching version 1.0 in late March. Would be good if there are no blocking issues for packaging.

**Comment by drew-parsons** [comment]
In the short term I've worked around it by patching out the setuptools_scm configuration.  We can continue doing that until we tracked down how SETUPTOOLS_SCM_PRETEND_VERSION gets used.

SETUPTOOLS_SCM_PRETEND_VERSION is referenced in /usr/share/perl5/Debian/Debhelper/Buildsystem/pybuild.pm from the debian dh-python package. I'm trying to confirm if the code path using it gets activated during the h5netcdf build.

**Comment by kmuehlbauer** [comment]
Thanks, good to hear you have a working state. I'll leave this open until resolved.

**Comment by drew-parsons** [comment]
I think I can see what's going on Setting SETUPTOOLS_SCM_PRETEND_VERSION explictly will no doubt work, but the debian pybuild tool already provides management of the variable.  What pybuild does is check whether setuptools-scm has been included in the build dependencies for the package. If so, then pybuild uses the debian build configuration to set a value for SETUPTOOLS_SCM_PRETEND_VERSION (if it isn't already set).

So the solution for the debian package is simple: just need to add Build-Depends: python3-setuptools-scm to the package.
With that done, we can close this Issue.

**Comment by kmuehlbauer** [comment]
Yes sorry, this will be fixed in #158.

**Comment by drew-parsons** [comment]
Looks like it's under control then.  The problem I reported here is a build configuration issue, not a h5netcdf issue, so I'll close this issue now.

**Comment by drew-parsons** [comment]
Great.  I'll package 0.15.0 once it's done.
