### ISSUE TITLE
AttributeError is raised when printing attributes object of a file from HSDS

### ISSUE THREAD

**Issue by TManhente** [h5netcdf/h5netcdf#161]
#### What happened:

Trying to print the attributes object of an HDF5 file from an HSDS server opened using `h5netcdf` raises an `AttributeError` since version 0.14.1:

```
  File "/h5/venv/h5netcdf-0.14.1/lib/python3.9/site-packages/h5netcdf/attrs.py", line 32, in __getitem__
    attr = self._h5attrs.get_id(key)
AttributeError: 'AttributeManager' object has no attribute 'get_id'
```

This also happens if you simply try to print the file object.

#### What you expected to happen:

No exception is raised and a summary of the file attributes is shown.

#### MCVE Code Sample
A running HSDS instance with an HDF5 file loaded to it is needed. Adjust the server URL and set the `HS_USERNAME` and `HS_PASSWORD` environment variables if access credentials are needed.

```python
import h5netcdf
file = h5netcdf.File('http://sn:5101/home/tall.h5', 'r', decode_vlen_strings=True)

# Both statements bellow raise an AttributeError since version 0.14.1:
print(file)
print(file.attrs)
```

Output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/h5/venv/h5netcdf-0.14.1/lib/python3.9/site-packages/h5netcdf/attrs.py", line 99, in __repr__
    ["%r" % type(self)] + ["%s: %r" % (k, v) for k, v in self.items()]
  File "/h5/venv/h5netcdf-0.14.1/lib/python3.9/site-packages/h5netcdf/attrs.py", line 99, in <listcomp>
    ["%r" % type(self)] + ["%s: %r" % (k, v) for k, v in self.items()]
  File "/usr/lib/python3.9/_collections_abc.py", line 850, in __iter__
    yield (key, self._mapping[key])
  File "/h5/venv/h5netcdf-0.14.1/lib/python3.9/site-packages/h5netcdf/attrs.py", line 32, in __getitem__
    attr = self._h5attrs.get_id(key)
AttributeError: 'AttributeManager' object has no attribute 'get_id'
```

#### Expected Output
Output generated from version 0.13.1:
```python
>>> file
<h5netcdf.File 'tall.h5' (mode r)>
Dimensions:
Groups:
    g1
    g2
Variables:
Attributes:
    attr1: array([ 97,  98,  99, 100, 101, 102, 103, 104, 105,   0], dtype=int8)
    attr2: array([[0, 1],
       [2, 3]], dtype=int32)
>>> file.attrs
<class 'h5netcdf.attrs.Attributes'>
attr1: array([ 97,  98,  99, 100, 101, 102, 103, 104, 105,   0], dtype=int8)
attr2: array([[0, 1],
       [2, 3]], dtype=int32)
```

#### Anything else we need to know?:

The HSDS server used was the default `hdfgroup/hsds:v0.6.3` Docker image from the Docker Hub. The [example `tall.h5` file](https://raw.githubusercontent.com/HDFGroup/h5serv/dde368d32ccd7a70975c91ee30ac8e75d1dca5ce/test/test_files/tall.h5) loaded to the HSDS server was taken from the [h5pyd](https://github.com/HDFGroup/h5pyd) repository. 

#### Version

<details><summary>Output of <tt>print(h5py.version.info, f"\nh5netcdf {h5netcdf.__version__}")</tt></summary>

**Version working fine:**
`0.13.1`:
```
Summary of the h5py configuration
---------------------------------

h5py    3.6.0
HDF5    1.12.1
Python  3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.22.3
cython (built with) 0.29.24
numpy (built against) 1.19.3
HDF5 (built against) 1.12.1

h5netcdf 0.13.1
```

**Versions raising `AttributeError`:**
`0.14.1`:
```
Summary of the h5py configuration
---------------------------------

h5py    3.6.0
HDF5    1.12.1
Python  3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.22.3
cython (built with) 0.29.24
numpy (built against) 1.19.3
HDF5 (built against) 1.12.1

h5netcdf 999
```

`0.15.0`:
```
Summary of the h5py configuration
---------------------------------

h5py    3.6.0
HDF5    1.12.1
Python  3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.22.3
cython (built with) 0.29.24
numpy (built against) 1.19.3
HDF5 (built against) 1.12.1

h5netcdf 0.15.0
```

All versions were installed on a Debian 11.2 machine using PIP in its standard Python package (version 3.9.2) and.

</details>

**Comment by kmuehlbauer** [comment]
@TManhente Thanks for raising this  and the thorough wrtite-up. The issue is, that `h5netcdf` is using some of `h5py's` low-level API, which is not available within `h5pyd` via `HSDS`.

More context and a suggested solution in #89. Which isn't implemented yet, unfortunately.

@ajelenak @jreadey Do you have thoughts on how to quickly work around the usage of low-level `h5py` calls to prevent `h5netcdf` breakages using `HSDS`? `h5netcdf` release 1.0 is planned for late March and it would be good to have at least a basic `h5pyd`/`H5DS` support. We could probably just wrap the above mentioned code with the high-level version (with a loss of feature). I can have a look the next days.

**Comment by ajelenak** [comment]
We have been working on this in the background. A lot of the foundation to bring back h5pyd/HSDS is now in place. However, h5netcdf continues its development and so is a moving target to catch up.

I have a branch where HSDS start up and shut down are a pytest session fixture. Using that, there are currently 14 failing h5netcdf tests, all due to `AttributeError: 'GroupID' object has no attribute 'get_create_plist'` So adding this method to h5pyd seems like the obvious next step. But not sure if we can meet the release deadline.

**Comment by kmuehlbauer** [comment]
@ajelenak Thanks for the heads-up and your efforts on that. I hope with the current status (as within your `hsds-pytest` branch) the work towards that goal can continue, as this will be the status for version 1.0. There will be no further changes which might introduce new calls of the h5py low-level api ( at least none that I can see atm), so you can assume a sitting target now. If there is anything I can do to help you with, please let me know. 

And even if the release deadline can't be made, which is likely the case as it's only days from now, it's good to see things progressing. So from my understanding the changes will be applied to `h5pyd` so no changes are needed to `h5netcdf` in that sense, right? And the testing feature could then be applied to any version after h5netcdf 1.0?

**Comment by kmuehlbauer** [comment]
@TManhente I'd appreciate if you could test latest h5netcdf main branch. At least you should not experience the reported error anymore. If this works for you, I'd go for a 0.15.1 release the next days.

**Comment by TManhente** [comment]
@kmuehlbauer, I've just tried it and the `AttributeError` is gone: Both printing the `file` or the `file.attrs` all worked fine!

**Comment by kmuehlbauer** [comment]
Thanks for checking this. If you encounter any other issues using HSDS/ h5pyd when using h5netcdf please open new issues.
