### ISSUE TITLE
Can numpy objects be supported?

### ISSUE THREAD

**Issue by adam2392** [h5netcdf/h5netcdf#164]
#### What happened:
I am using `netcdf` to save `xarray` objects containing a list of lists (or numpy array of objects) inside the metadata. However, since numpy arrays are not supported, I convert this to a list of lists. When saving, I run into a Deprecation Warning and then a TypeError.

I wonder if this is the best place to solve it?

#### What you expected to happen:
Ideally, h5netcdf realizes this is a list of lists with different lengths, and converts it to numpy object rather then numpy array.

#### MCVE Code Sample
Using `mne-python` and `mne-connectivity`

```python
import numpy as np
from mne import EpochsArray, create_info
from mne_connectivity import spectral_connectivity_epochs

    rng = np.random.RandomState(0)
    n_epochs, n_chs, n_times, sfreq, f = 10, 2, 2000, 1000., 20.
    data = rng.randn(n_epochs, n_chs, n_times)
    sig = np.sin(2 * np.pi * f * np.arange(1000) / sfreq) * np.hanning(1000)
    data[:, :, 500:1500] += sig
    info = create_info(n_chs, sfreq, 'eeg')
    tmin = -1
    epochs = EpochsArray(data, info, tmin=tmin)

    conn = spectral_connectivity_epochs(epochs, 
        fmin=(4, 8, 13, 30), fmax=(8, 13, 30, 45), faverage=True)
    conn.save('foo.nc')
```

we get the error message:

```
mne_connectivity/spectral/tests/test_spectral.py:569: in test_save
    conn.save('foo.nc')
mne_connectivity/base.py:828: in save
    self.xarray.to_netcdf(fname, mode='w',
.venv/lib/python3.9/site-packages/xarray/core/dataarray.py:2846: in to_netcdf
    return dataset.to_netcdf(*args, **kwargs)
.venv/lib/python3.9/site-packages/xarray/core/dataset.py:1900: in to_netcdf
    return to_netcdf(
.venv/lib/python3.9/site-packages/xarray/backends/api.py:1072: in to_netcdf
    dump_to_store(
.venv/lib/python3.9/site-packages/xarray/backends/api.py:1119: in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
.venv/lib/python3.9/site-packages/xarray/backends/common.py:265: in store
    self.set_variables(
.venv/lib/python3.9/site-packages/xarray/backends/common.py:303: in set_variables
    target, source = self.prepare_variable(
.venv/lib/python3.9/site-packages/xarray/backends/h5netcdf_.py:339: in prepare_variable
    nc4_var.attrs[k] = v
.venv/lib/python3.9/site-packages/h5netcdf/attrs.py:76: in __setitem__
    dtype = np.asarray(value).dtype
E   numpy.VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
```

```
mne_connectivity/spectral/tests/test_spectral.py:570: in test_save
    conn.save('foo.nc')
mne_connectivity/base.py:828: in save
    self.xarray.to_netcdf(fname, mode='w',
.venv/lib/python3.9/site-packages/xarray/core/dataarray.py:2846: in to_netcdf
    return dataset.to_netcdf(*args, **kwargs)
.venv/lib/python3.9/site-packages/xarray/core/dataset.py:1900: in to_netcdf
    return to_netcdf(
.venv/lib/python3.9/site-packages/xarray/backends/api.py:1072: in to_netcdf
    dump_to_store(
.venv/lib/python3.9/site-packages/xarray/backends/api.py:1119: in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
.venv/lib/python3.9/site-packages/xarray/backends/common.py:265: in store
    self.set_variables(
.venv/lib/python3.9/site-packages/xarray/backends/common.py:303: in set_variables
    target, source = self.prepare_variable(
.venv/lib/python3.9/site-packages/xarray/backends/h5netcdf_.py:339: in prepare_variable
    nc4_var.attrs[k] = v
.venv/lib/python3.9/site-packages/h5netcdf/attrs.py:79: in __setitem__
    self._h5attrs[key] = value
h5py/_objects.pyx:54: in h5py._objects.with_phil.wrapper
    ???
h5py/_objects.pyx:55: in h5py._objects.with_phil.wrapper
    ???
.venv/lib/python3.9/site-packages/h5py/_hl/attrs.py:103: in __setitem__
    self.create(name, data=value)
.venv/lib/python3.9/site-packages/h5py/_hl/attrs.py:180: in create
    htype = h5t.py_create(original_dtype, logical=True)
h5py/h5t.pyx:1663: in h5py.h5t.py_create
    ???
h5py/h5t.pyx:1687: in h5py.h5t.py_create
    ???
h5py/h5t.pyx:1747: in h5py.h5t.py_create
    ???
E   TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

#### Version

<details><summary>Output of <tt>print(h5py.version.info, f"\nh5netcdf {h5netcdf.__version__}")</tt></summary>

Summary of the h5py configuration
---------------------------------

h5py    3.6.0
HDF5    1.12.1
Python  3.9.5 (default, May 18 2021, 12:31:01) 
[Clang 10.0.0 ]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.22.2
cython (built with) 0.29.24
numpy (built against) 1.19.3
HDF5 (built against) 1.12.1
 
h5netcdf 999

</details>

**Comment by kmuehlbauer** [comment]
@adam2392 Thanks for raising this. A pure `h5netcdf` MCVE would be nice nevertheless. 

For [NetCDF4 data model](https://docs.unidata.ucar.edu/netcdf-c/current/netcdf_data_model.html) 

> Attributes are always scalar values or 1D arrays, which can be associated with either a variable or the file as a whole. Although there is no enforced limit, the user is expected to keep attributes small. 

So this means that this would be a non-standard usage which `h5netcdf` could only support using `invalid_netcdf` keyword arg. 

Also [HDF5](https://confluence.hdfgroup.org/display/HDF5/Attributes) speaks of Attributes as small datasets. 

> How small is "small" is not defined by the library and is up to the user’s interpretation.

As the request is not conforming to the NetCDF4 standard I'm inclined to keep the current behavior. You might go the suggested way (HDF5-link above) of adding the data as another variable with an attribute pointing to the it.

**Comment by kmuehlbauer** [comment]
Xref: https://github.com/mne-tools/mne-connectivity/issues/87

**Comment by kmuehlbauer** [comment]
After reading the discussion over at https://github.com/mne-tools/mne-connectivity/issues/87 I think I might be missing a bit of context. 

@adam2392 In the [mne-connectivity docs](https://mne.tools/mne-connectivity/stable/generated/mne_connectivity.Connectivity.html?highlight=save#mne_connectivity.Connectivity.save) the output format is mentioned as NetCDF. What you request would finally create non-standard NetCDF files. Maybe I'm missing something. Could you shed some light?

**Comment by shoyer** [comment]
It isn't possible to directly put arbitrary NumPy object arrays into HDF5 files, because these can contain arbitrary Python objects that may not be supported by HDF5.

If desired, arbitrary Python objects could be serialized into bytes with [pickle](https://docs.python.org/3/library/pickle.html). But this would not be appropriate for h5netcdf unless users need to explicitly opt-in each time they open a file with pickle support (e.g., by specifying something like `allow_pickle=True`), because deserializing pickle data allows arbitrary code execution.

**Comment by kmuehlbauer** [comment]
I'm closing this as wont-fix. If there is more discussion needed, please reopen @adam2392.
