### ISSUE TITLE
h5netcdf writes invalid netcdf to existing netcdf files

### ISSUE THREAD

**Issue by kmuehlbauer** [h5netcdf/h5netcdf#165]
#### What happened:

While exploring #164 I've found that currently `h5netcdf` is able to write invalid netcdf data to existing netcdf4 files, when the file is opened with `invalid_netcdf=True`. Unfortunately this leaves the `_NCProperties` intact. 

#### What you expected to happen:

`_NCProperties` should be removed from the file, when writing with `invalid_netcdf=True`.

#### MCVE Code Sample

```python
# Your code here
import numpy
import netCDF4
import h5netcdf

with netCDF4.Dataset("test.nc", mode="w") as ds:
    pass
with h5netcdf.File("test.nc", mode="a", invalid_netcdf=True) as ds:
    print("before write invalid:", ds._h5file.attrs["_NCProperties"])
    arr = numpy.zeros(10, dtype=numpy.bool_)
    ds.create_variable("test", ("x",), data=arr)
with h5netcdf.File("test.nc", mode="r") as ds:
    print("after write invalid:", ds._h5file.attrs["_NCProperties"])

before write invalid: b'version=2,netcdf=4.8.1,hdf5=1.12.1'
after write invalid: b'version=2,netcdf=4.8.1,hdf5=1.12.1'
```

#### Expected Output

The `_NCProperties` attribute should be removed, indicating that this is not a NetCDF4 compliant file.

#### Anything else we need to know?:

The main problem is that currently the logic to write `_NCProperties` applies only to not existing files. For preexisting files `_NCProperties` will be left intact if invoked with `invalid_netcdf=True`. 

#### Version

<details><summary>Output of <tt>print(h5py.version.info, f"\nh5netcdf {h5netcdf.__version__}")</tt></summary>

Summary of the h5py configuration
---------------------------------
h5py    3.6.0
HDF5    1.12.1
Python  3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
[GCC 9.4.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.20.0
cython (built with) 0.29.27
numpy (built against) 1.20.0
HDF5 (built against) 1.12.1
 
h5netcdf 0.16.0.dev3+g2324ff2
</details>

**Comment by kmuehlbauer** [comment]
It looks like this behavior is there for a very long time.

There are at least two solutions to this problem:

- do not allow appending invalid netcdf data to a NetCDF4 conforming file (having `_NCProperties`), allow only newly created files with invalid netcdf data (they will miss the `_NCProperties`
- remove `_NCProperties` when appending invalid netcdf data to an existing file

As writing of invalid netcdf data can only happen if invoked with `invalid_netcdf=True` the user should know what he's doing so I would go for the second approach removing an existing `_NCProperties`.

@shoyer It would be great if you could share your thoughts on that issue.

**Comment by kmuehlbauer** [comment]
Please have a look at a possible fix in #166.

We do not write `_NCProperties` when creating a file from scratch with invalid netcdf features. So it is fitting to assume that we should remove `_NCProperties` when writing invalid netcdf features to an existing (valid) file. 

As users might still use `.nc` extension when writing invalid netcdf features a `UserWarning` is displayed:

> UserWarning: You are writing invalid netcdf features to file `test.nc`. The file will thus be not conforming to NetCDF-4 standard and might not be readable by other netcdf tools. Consider using a different extension.

**Comment by kmuehlbauer** [comment]
I've opened a discussion over at unidata: [How does netcdf-c recognize netCDF4 format](https://github.com/Unidata/netcdf-c/discussions/2258).

**Comment by shoyer** [comment]
> * remove `_NCProperties` when appending invalid netcdf data to an existing file

This solution sounds good to me!

**Comment by kmuehlbauer** [comment]
Thanks Stephan, much appreciated.
