### ISSUE TITLE
Corrupted headers when serialising using dask.distributed client

### ISSUE THREAD

**Issue by aidanheerdegen** [h5netcdf/h5netcdf#170]
#### MCVE Code Sample
I haven't managed to produce a MCVE that reproduces this behaviour, but thought it was better to report even without this. So the code l[oads UM data files using the the Iris package](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/fileformats/um.html) and then outputs the data to a netCDF file.
```python
cube = iris.load(ifiles, constraints=stash_const)
engine = 'h5netcdf'
for c in cube:
    ds = xr.DataArray.from_iris(c)
    ds.to_netcdf(ofile, engine=engine)
```
#### Expected Output

When `engine = 'netdf4'` or when `engine = 'h5netcdf'` and there is no `dask.distributed` client enabled the header looks like this:
```
netcdf test_netcdf4 {
dimensions:
	time = 120 ;
	latitude = 459 ;
	longitude = 798 ;
```
When `engine = 'h5netcdf'` and there is a `dask.distributed` client enabled the header looks like this:
```
netcdf test_h5netcdf {
dimensions:
	time = 120 ;
	time = 120 ;
	longitude = 798 ;
```

#### Anything else we need to know?:

It looks like when there is a `dask.distributed` client enabled more than one process is trying to define the netCDF header leading to it being corrupted.

This does not happen with an older version of `h5netcdf`. It serialises without error with or without a dask client enabled. tThe version details for this older working config:
<details><summary>Output of <tt>print(h5py.version.info, f"\nh5netcdf {h5netcdf.__version__}")</tt> for working version</summary>
Summary of the h5py configuration
---------------------------------

h5py    3.6.0
HDF5    1.10.6
Python  3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
[GCC 9.4.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.22.0
cython (built with) 0.29.24
numpy (built against) 1.16.6
HDF5 (built against) 1.10.6
 
h5netcdf 0.12.0
</details>

#### Version

<details><summary>Output of <tt>print(h5py.version.info, f"\nh5netcdf {h5netcdf.__version__}")</tt></summary>

Summary of the h5py configuration
---------------------------------

h5py    3.6.0
HDF5    1.12.1
Python  3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59) 
[GCC 10.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.21.6
cython (built with) 0.29.24
numpy (built against) 1.19.5
HDF5 (built against) 1.12.1
 
h5netcdf 1.0.0
</details>

**Comment by kmuehlbauer** [comment]
@aidanheerdegen Thanks for raising this. A MCVE would be really great to help this tracking down. Could be a file locking issue, but that's just guesswork.

**Comment by aidanheerdegen** [comment]
I'd love to, but am very busy right now, and find trying to make MCVEs reproduce errors can be a time consuming process in some cases. When I have a chance I'll try and come back to it. I hoped the fact that it worked in previous versions might be enough of a clue to zero in on changes since then that could be the culprit.

**Comment by kmuehlbauer** [comment]
There has been a lot of changes to the dimension handling since version 0.12. It will be a hard undertaking to figure this out without example code. I'd have a look into this, but I need at least something I can work with. 

- An example data file would be nice, or at least information about the `CubeList` you are iterating over
- How is dask distributed enabled? 
- Is your above example code exactly like this? Without specifying `mode='a'` `ofile` gets overwritten for every iteration.

As you said, creating a MCVE can be a time consuming process. If this behavior shows up more frequently, good chance that others will report similar problems.

**Comment by aidanheerdegen** [comment]
Point taken. It's not my code, I was just alerted to the problem by someone and thought I should report it.

The client is just a default local `dask.distributed` client.
```python
    client       = dask.distributed.Client()
```
The data was someone else's but here is the dataset being converted:
```
<xarray.DataArray 'surface_downward_northward_stress' (time: 120, latitude: 459, longitude: 798)>
dask.array<filled, shape=(120, 459, 798), dtype=float32, chunksize=(1, 459, 798), chunktype=numpy.ndarray>
Coordinates:
  * time                     (time) datetime64[ns] 2012-09-01T03:00:00 ... 20...
  * latitude                 (latitude) float32 -55.35 -55.2 ... 15.25 15.41
  * longitude                (longitude) float32 86.34 86.49 ... 209.3 209.5
    forecast_reference_time  datetime64[ns] ...
    forecast_period          (time) timedelta64[ns] ...
Attributes:
    standard_name:  surface_downward_northward_stress
    units:          Pa
    source:         Data from Met Office Unified Model
    um_version:     11.9
    STASH:          m01s03i461
    cell_methods:   time: mean (interval: 1 hour)
```
There are 120 individual files each with a single timestep. I'll try and reduce the data to as few files as possible, and maybe try uploading them somewhere if I can get it small enough when I have time.

**Comment by kmuehlbauer** [comment]
Reporting issues is a good idea anyway, so thanks for taking time reporting this. Looking forward to anything you can provide to narrow this down. I'll try searching through the code for possible points of failure in the meantime (when I can free some time).

**Comment by kmuehlbauer** [comment]
@aidanheerdegen Did you come any further with that issue? I would try to look into this if you could provide more information, MCVE would be nice.

**Comment by aidanheerdegen** [comment]
Sorry, I am snowed under with work right now. I won't have time to look into this further as I am changing roles soon.

**Comment by kmuehlbauer** [comment]
Thanks for coming back to this. Would you be able to provide a test UM file which broke with your setup?

**Comment by kmuehlbauer** [comment]
I'm closing this now. Feel free to re-open with additional detail or open a new issue.
