### ISSUE TITLE
Remove h5py2 related code and CI builds

### ISSUE THREAD

**Issue by kmuehlbauer** [h5netcdf/h5netcdf#176]
As h5py version 2.10 is now succeeded by h5py version 3 (we are already at 3.7.0) would it make sense to remove the h5py version 2 related code?

Is there anyone out there using h5py version 2 for some reason that we should maintain the tests for version 2?

**Comment by mathause** [comment]
You could consider adapting NEP 29 - e.g. xarray currently supports h5py v3.1 and up.

https://github.com/pydata/xarray/blob/3f7cc2da33d81e76afbfb82da57143b624b03a88/ci/requirements/min-all-deps.yml#L22

**Comment by kmuehlbauer** [comment]
I've found the [hdf5 release schedule](https://www.hdfgroup.org/2022/06/2022-hdf5-release-schedule/). So hdf5 v1.8 line will be EOL by end of this year and v1.10 line is supposed to be alive to the end of next year (currently at v1.10.9). So I'm inclined to postpone the removal of h5py2 compatibility code until v1.10 EOL. 

Unfortunately conda-forge hdf5 is stuck at v1.10.6, so we can't test the latest version.

I'll close this for now.

**Comment by kmuehlbauer** [comment]
This got finally resolved by #194 after discussion in #191.
