### ISSUE TITLE
Documentation request: Alternative way to obtain h5netcdf

### ISSUE THREAD

**Issue by Hellseher** [h5netcdf/h5netcdf#200]
Hi,

As the project is packed and availalbe via [Guix](https://guix.gnu.org/) it may be mentioned as one of the alternative way to install it:

``` shell
guix install python-h5netcdf
```
https://packages.guix.gnu.org/packages/python-h5netcdf/

It may help to reproduce development environment 1:1 on other hosts, which includes not just Python dependencies but the whole system itself.

Thanks,
Oleg

**Comment by kmuehlbauer** [comment]
Thanks @Hellseher, nice to see `h5netcdf` is a useful library to get packaged. I'd suggest to add some paragraph to the end of the install section mentioning that h5netcdf is also available via  `Guix` and others (eg. debian and other linux distros).
