### ISSUE TITLE
Modifying attributes safely is not possible with all datasets.

### ISSUE THREAD

**Issue by Frooob** [h5netcdf/h5netcdf#207]
#### What happened:
I'm trying to modify attributes in a local copy of a CMIP dataset. However, it's only possible to modify the attributes once, for the second time theres an error 'KeyError: 'Unable to delete attribute (record is not in B-tree)'

#### MCVE Code Sample

```python
import h5netcdf
import xarray as xr

ds = xr.open_zarr("gs://cmip6/CMIP6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/day/tas/gn/v20190710/")

testfile = "test.nc"

ds = ds.isel(time = slice(None, 10)) # reduce file size.
ds.to_netcdf(testfile)

with h5netcdf.File(testfile, "r+") as f:
    f.attrs["variable_id"] = "changed_with_h5netscdf"

with h5netcdf.File(testfile, "r+") as f:
    f.attrs["variable_id"] = "changed_with_h5netscdf_again"
```
When writing the attribute the second time, the execution fails with:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/example_code.py in line 11
      8     f.attrs["variable_id"] = "changed_with_h5netscdf"
     10 with h5netcdf.File(testfile, "r+") as f:
---> 11     f.attrs["variable_id"] = "changed_with_h5netscdf_again"

File ~/conda_env/lib/python3.8/site-packages/h5netcdf/attrs.py:86, in Attributes.__setitem__(self, key, value)
     83     dtype = np.asarray(value).dtype
     85 self._check_dtype(dtype)
---> 86 self._h5attrs[key] = value

File h5py/_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py/_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File ~/opt/miniconda3/envs/pyrepath-env/lib/python3.8/site-packages/h5py/_hl/attrs.py:103, in AttributeManager.__setitem__(self, name, value)
     95 @with_phil
     96 def __setitem__(self, name, value):
     97     """ Set a new attribute, overwriting any existing attribute.
     98 
     99     The type and shape of the attribute are determined from the data.  To
    100     use a specific type or shape, or to preserve the type of an attribute,
    101     use the methods create() and modify().
    102     """
...
File h5py/_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File h5py/h5a.pyx:145, in h5py.h5a.delete()

KeyError: 'Unable to delete attribute (record is not in B-tree)'

```

#### Anything else we need to know?:

After modifying attributes with h5netcdf, the file cannot be opened with the netcdf4 library anymore (with "r+" option). Xarray however can still open and modify the file (it doesn't modify inplace though). I'm guessing, h5netcdf corrupts the file in the process of writing the attributes.

This issue doesn't arise with all datasets. In particular, if the dataset is saved with the option `engine='h5netcdf'` it is possible to write the attributes multiple times. 

I'm not sure, if the h5netcdf library is even supposed to be able to write datasets, that are not written with the h5netcdf engine. But if that is not the case, if its possible, it might be a good idea not allowing to write the attributes in the datasets in the first place in order to not leave corrupted files. 

#### Version

Summary of the h5py configuration
---------------------------------

h5py    3.6.0
HDF5    1.12.1
Python  3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:05:47) 
[Clang 12.0.1 ]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.23.4
cython (built with) 0.29.24
numpy (built against) 1.18.5
HDF5 (built against) 1.12.1
 
h5netcdf 1.1.0
xarray 0.20.1

**Comment by kmuehlbauer** [comment]
@Frooob Thanks for raising this. Unfortunately that error is originating from hdf5.

Please have a look in

https://github.com/h5py/h5py/issues/1385

and 

https://github.com/HDFGroup/hdf5/issues/1388

for more context.

I've tried to fix this over at hdf5, but unfortunately my C/C++ skills are not sufficient for that task.

If you strongly rely on that feature, please try to convince upstream to fix this.

**Comment by kmuehlbauer** [comment]
I've updated my issue over at https://github.com/HDFGroup/hdf5/issues/1388. Let's see if there will be any movement.

**Comment by kmuehlbauer** [comment]
@Frooob After recollecting my thoughts on that issue, we might actually be able to make this work by changing h5py.

In your use-case the dtype of your attribute is the same throughout consecutive changes, right?

**Comment by Frooob** [comment]
Yes, nothing in the dataset besides the attributes should be changing

**Comment by kmuehlbauer** [comment]
@Frooob 

Currently setting an existing attribute via h5py is creating an new temporary attribute,  deleting the existing attribute followed by renaming the temporary attribute to the existing name. That deletion/rename is the source of our issue, as it triggers the above mentioned bug in hdf5.

We could just try to modify the existing attribute, but we will be bound to the existing datatype. In the case of your `variable_id` this is a fixed length string of size 3:

```
HDF5 "test.nc" {
ATTRIBUTE "variable_id" {
   DATATYPE  H5T_STRING {
      STRSIZE 3;
      STRPAD H5T_STR_NULLTERM;
      CSET H5T_CSET_ASCII;
      CTYPE H5T_C_S1;
   }
   DATASPACE  SCALAR
   DATA {
   (0): "tas"
   }
}
}
```

Using h5py `AttributeManager`'s `modify`-function we can change the content to another fixed length-string of size 3. But we can only change it to a fixed length string of size 2, since h5py uses `NULLPAD` but the origin uses `NULLTERM` (most likely netcdf-c).

To establish an extendable string you would need to delete and recreate the attribute as variable length string:

```python
with h5netcdf.File(testfile, "r+") as f:
    print(f.attrs["variable_id"])
    del f.attrs["variable_id"]
    # create variable-length string
    f.attrs["variable_id"] = b"changed_with_h5netcdf"
    print(f.attrs["variable_id"])
with h5netcdf.File(testfile, "r+") as f:
    print(f.attrs["variable_id"])
    # call h5py-modify
    f.attrs._h5attrs.modify("variable_id", b"changed_with_h5netcdf_again")
    print(f.attrs["variable_id"])
with h5netcdf.File(testfile, "r+") as f:
    print(f.attrs["variable_id"])
    # call h5py-modify
    f.attrs._h5attrs.modify("variable_id", b"changed_with_h5netcdf_again_and_again_to_make_up_for_a_huge_string")
    print(f.attrs["variable_id"])
```
```
tas
changed_with_h5netcdf
changed_with_h5netcdf
changed_with_h5netcdf_again
changed_with_h5netcdf_again
changed_with_h5netcdf_again_and_again_to_make_up_for_a_huge_string
```

To me, it looks like this change is best located upstream at h5py. I'll open an issue in h5py.

**Comment by kmuehlbauer** [comment]
@Frooob I've opened a PR over at https://github.com/h5py/h5py/pull/2206.

It might nevertheless be a good idea to add that workaround in h5netcdf to cover for older h5py releases.

**Comment by Frooob** [comment]
Wow really cool, in our code I have also implemented the workaround now, checking if the type of the attribute already is a string with variable size and only then use modify, if it's a fixed size string, delete the attribute and create a new one. I'm already quite happy with that. 😄

**Comment by kmuehlbauer** [comment]
@Frooob Just a heads-up, the above mentioned issue was upleveled to `Priority High 1.` at HDF5 Group. So we might just wait it out, now.

**Comment by Frooob** [comment]
This is fixed in h5py (https://github.com/h5py/h5py/pull/2274)
