### ISSUE TITLE
md5 checksum mismatch for identical files/data

### ISSUE THREAD

**Issue by abunimeh** [h5netcdf/h5netcdf#211]
#### What happened:
Performing an md5 checksum on files produced using h5netcdf results in a mismatch. Same code works using a different engine e.g. `netcdf4`

#### What you expected to happen:
md5 checksum match

#### MCVE Code Sample

```python
import pandas as pd
import hashlib
import xarray as xr
from time import sleep


def check_xr(xrds):
    fname1 = "./sample1.nc"
    fname2 = "./sample2.nc"

    xrds.to_netcdf(
        fname1,
        engine="h5netcdf",
    )
    print("sample1.nc: ", end="")
    s1hash = hashlib.md5(open(fname1, "rb").read()).hexdigest()
    print(s1hash)

    # comment this sleep statement and the hashes will match
    sleep(5)
    samedata = xr.load_dataset(fname1)
    samedata.to_netcdf(
        fname2,
        engine="h5netcdf",
    )
    print("sample2.nc: ", end="")
    s2hash = hashlib.md5(open(fname2, "rb").read()).hexdigest()
    print(s2hash)

    if s1hash == s2hash:
        print("✅ md5 checksums are equal")
    else:
        print("❌ md5 checksums are NOT equal")

    if samedata.identical(xrds):
        print("✅ xarray.identical() ? True: datasets are identical")
    else:
        print("❌ xarray.identical() ? False: datasets are NOT identical")

    print("### original DS: ")
    print(xrds)

    print("### readback DS: ")
    print(samedata)


### case 1:
d = {"col1": [1, 2], "col2": [3, 4]}
df = pd.DataFrame(data=d)
ds = df.to_xarray()
check_xr(ds)

```

#### Expected Output
comment out sleep statement and result checksum will match

#### Version

<details><summary>Output of <tt>print(h5py.version.info, f"\nh5netcdf {h5netcdf.__version__}")</tt></summary>

h5py    3.8.0
HDF5    1.12.2
Python  3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.24.2
cython (built with) 0.29.33
numpy (built against) 1.21.6
HDF5 (built against) 1.12.2
 
h5netcdf 1.1.0

</details>

**Comment by kmuehlbauer** [comment]
Thanks @abunimeh for raising this.

Can you, by chance, create a MCVE with h5netcdf only?

**Comment by abunimeh** [comment]
MCVE

```python
import h5netcdf
from time import sleep

with h5netcdf.File("sample1.nc", "w") as f1:
    f1.dimensions = {"x": 5}
    v = f1.create_variable("hello", ("x",), float)
    v[:] = [1, 1, 1, 1, 1]

# comment out this line and the md5 checksum will match
sleep(5)

with h5netcdf.File("sample2.nc", "w") as f2:
    f2.dimensions = {"x": 5}
    v = f2.create_variable("hello", ("x",), float)
    v[:] = [1, 1, 1, 1, 1]
```

without sleep() md5 checksum matches
```
md5 sample1.nc sample2.nc                                             
MD5 (sample1.nc) = 5a8ece3bce095ae7d651936306e21351
MD5 (sample2.nc) = 5a8ece3bce095ae7d651936306e21351
```

it looks like data/time of creation is embedded in the file which is causing the file to have different checksums. It would be nice to prevent embedding such info inside the file that way the file checksum is always the same regardless of when it was created.

with sleep() md5 checksum doesn't match
```
md5 sample1.nc sample2.nc 
MD5 (sample1.nc) = eeeb814c19f9efbaeb1f062ac89bab0f
MD5 (sample2.nc) = 9f1703c5ef4bf27d4c10b93e724b35db
```

**Comment by kmuehlbauer** [comment]
Thanks @abunimeh for providing that minimal example.

I'll have a look if this is something h5netcdf can control.

**Comment by kmuehlbauer** [comment]
One thing you can try is setting `track_order=False` when opening.

It might have to do how hdf5 is keeping track of creation order. Not sure if we can do anything about it.

**Comment by abunimeh** [comment]
`track_order=False` fixes it

```python3
import h5netcdf
from time import sleep
import hashlib


track_order = False

fname1 = "./sample1.nc"
fname2 = "./sample2.nc"

with h5netcdf.File(fname1, "w", track_order=False) as f1:
    f1.dimensions = {"x": 5}
    v = f1.create_variable("hello", ("x",), float)
    v[:] = [1, 1, 1, 1, 1]

# comment out this line and the md5 checksum will match
sleep(5)

with h5netcdf.File(fname2, "w", track_order=False) as f2:
    f2.dimensions = {"x": 5}
    v = f2.create_variable("hello", ("x",), float)
    v[:] = [1, 1, 1, 1, 1]

s1hash = hashlib.md5(open(fname1, "rb").read()).hexdigest()
s2hash = hashlib.md5(open(fname2, "rb").read()).hexdigest()

assert s1hash == s2hash
```

**Comment by kmuehlbauer** [comment]
Great this works. But that comes with a cost. If you want to use it in your original use case, to create netcdf-files, then this might create issues down the road. By design netcdf-c and netcdf4-python use track_order=True to keep track of object creation order.

**Comment by abunimeh** [comment]
Thanks!
