### ISSUE TITLE
Question: does `h5netcdf` bring in the entire data from a netCDF file on a remote disk (like S3)? 

### ISSUE THREAD

**Issue by valeriupredoi** [h5netcdf/h5netcdf#215]
Hi guys, first off I wanted to thank you for building this library, I have recently (just today) came across it, and it does the job for my particular case: I am opening a netCDF4 file located on an S3 FS (in a bucket), and then using `h5netcdf` to have it like a netCDF file; netCDF4-python complained that the file is not "local", but `h5netcdf` is very nice and accomodating with the file sitting in an S3 bucket. See the minimal code below:

```python
    fs = s3fs.S3FileSystem(key=S3_ACCESS_KEY,  # eg "minioadmin" for Minio
                           secret=S3_SECRET_KEY,  # eg "minioadmin" for Minio
                           client_kwargs={'endpoint_url': S3_URL})  # eg "http://localhost:9000" for Minio
    with fs.open(uri, 'rb') as s3file:
        ds = h5netcdf.File(s3file, 'r', invalid_netcdf=True)
        print(f"Dataset loaded from S3 via h5netcdf: {ds}")
```

My very quick question to you, please: will `ds` (in this case), which is what the client sees of the netCDF file at location `uri` in the S3 bucket, contain the entire (very large, on occasion) data or is it just just a much smaller reference file with metadata, and just a pointer to the physical data? Very many thanks in advance :beer:

**Comment by shoyer** [comment]
Generally h5netcdf/h5py only load minimum required data, which in principle should be using something like a range-get for S3FileSytem.

That said, HDF5 was designed for local filesystems, so sometimes reading metadata can be more expensive than one would think. But it certainly should not be loading the entire thing...

**Comment by valeriupredoi** [comment]
Ih @bnlawrence doesn't have other q's, I can close this - great timely communication, cheers, guys!
