### ISSUE TITLE
legacy api: add isunlimited method

### ISSUE THREAD

**Issue by jhamman** [h5netcdf/h5netcdf#36]
For compatability with netCDF4-Python, it would be nice to have the `isunlimited` on variable objects:

reference: http://unidata.github.io/netcdf4-python/#netCDF4.Dimension.isunlimited
xref: https://github.com/pydata/xarray/pull/1637

**Comment by shoyer** [comment]
We don’t have notion of Dimension objects (yet) in h5netcdf. We just use integers, or None for unlimited.

**Comment by shoyer** [comment]
I suppose this would indeed make sense for the legacy API.

**Comment by kmuehlbauer** [comment]
> We don’t have notion of Dimension objects (yet) in h5netcdf. We just use integers, or None for unlimited.

A implementation of a Dimension-object is suggested in #134 and a WIP-PR is available #135 too.

**Comment by kmuehlbauer** [comment]
resolved by #135
