### ISSUE TITLE
Support _FillValue for variable length strings

### ISSUE THREAD

**Issue by shoyer** [h5netcdf/h5netcdf#37]
Current status:
- We can read them, for files written with netCDF4-python (via https://github.com/Unidata/netcdf4-python/pull/732).
- We can't write them, due to https://github.com/h5py/h5py/issues/941.

**Comment by kmuehlbauer** [comment]
Update: https://github.com/h5py/h5py/issues/941#issuecomment-1029756453

**Comment by kmuehlbauer** [comment]
Good news -> Possible fix in https://github.com/h5py/h5py/pull/2044

**Comment by kmuehlbauer** [comment]
https://github.com/h5py/h5py/pull/2044 is merged and available in h5py 3.7

**Comment by kmuehlbauer** [comment]
@shoyer This has now been fixed upstream and h5py 3.7.0 is available. I've added the necessary changes in #175. Would be great if you could have a look over there. Thanks!

**Comment by kmuehlbauer** [comment]
resolved by #175
