### ISSUE TITLE
suggestion - make it possible to use dimension objects instead of names

### ISSUE THREAD

**Issue by mangecoeur** [h5netcdf/h5netcdf#5]
in netcdf-python

``` python
lon_dim = dset.createDimension('lon', 80)

longitudes = dset.createVariable('lon', 'f4', ('lon',))
```

suggest to make it possible to use the dimension object as an alternative to using the dimension name:

``` python
lon_dim = dset.create_dimension('lon', 80)

longitudes = dset.create_variable('lon', 'f4', (lon_dim,))
```

**Comment by shoyer** [comment]
What's the use case for using dimension objects instead of names? I'm slightly reluctant to create a new type that without any additional functionality -- right now, we don't have a `Dimension` class at all.

**Comment by mangecoeur** [comment]
The createDimension function appears to return something in netcdf, though since you can't use it for anything in bout sure what type it is. The main use case is for catching bugs though static analysis. If you can use the object returned by the function, you can check that the variable has been created before using it. If you use the dimension name its impossible to tell if you are trying to use a dimension that hasn't been created until runtime.

-----Original Message-----

**Comment by shoyer** [comment]
For that use case, I guess it would suffice for create_dimension to simply return the name of the new dimension? That change is easy enough to make.

The new API based more directly on h5py (which I haven't released yet) also makes creating dimensions first optional, if you supply an array at creation time via the `data` argument.

**Comment by kmuehlbauer** [comment]
@mangecoeur Considering the age of this issue and the fact that this never was implemented, I'll close this. Feel free to reopen.

**Comment by kmuehlbauer** [comment]
@mangecoeur Time has come where a dedicated dimension class brings additional functionality. Please use #134 and #135 for discussion. Thanks.
