### ISSUE TITLE
problems with user defined types?

### ISSUE THREAD

**Issue by edwardhartnett** [h5netcdf/h5netcdf#70]
Howdy!

I'm the author of netcdf-4, and currently help maintain the C library. I just heard about this project and it looks really fun and interesting!

From a brief read of the docs, it seems that you don't believe vlens and some other user-defined types are not supported in netCDF. Everything should be supported except:
* transiant types (I just learned of them!)
* reference types (I can't figure out how to handle them.)
* circular group structures.

But things like vlens and other user-defined types should work.

Let me know if you have any questions about netcdf-c. Keep on netCDFing!

**Comment by shoyer** [comment]
Hi Edward, good to hear from you!

netCDF does support user-defined types, but unfortunately it can’t read user defined types written by h5py. That’s all I intended to imply with the statement in the README.

It actually looks like we talked about this a few years ago: https://github.com/Unidata/netcdf-c/issues/267

Cheers,
Stephan

**Comment by kmuehlbauer** [comment]
I think most of the issues have been solved or worked around now. I'm closing this issue, please feel free to open new issues as needed.

@edwardhartnett Thanks for improving netcdf-c! Here at h5netcdf we try to catch-up with the latest developments to create a nice downstream users experience.
