### ISSUE TITLE
Changes floating point values to rounded integers

### ISSUE THREAD

**Issue by KillerStrike17** [h5netcdf/h5netcdf#71]
if i have a value like 3.76412, when i read it it converts the value to 376, and if the value is 3.7677 it converts to 377

**Comment by shoyer** [comment]
I’m not quite sure what you mean. h5netcdf itself doesn’t any logic for doing something like this, so I suspect the culprit is something else in the stack. Could you share a code example?

**Comment by kmuehlbauer** [comment]
@KillerStrike17 If this is still relevant, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by kmuehlbauer** [comment]
Please reopen with minimal reproducible example.
