### ISSUE TITLE
pytest failures

### ISSUE THREAD

**Issue by jreadey** [h5netcdf/h5netcdf#79]
Hi,

  I built from master with Python 3.8, h5py 2.10.0, netCDF4 1.5.4, and hdf5 1.10.4. 

  Running py.test -v h5netcdf/  (with WITHRESTAPI not set) I got the following two failures:

    FAILED h5netcdf/tests/test_h5netcdf.py::test_invalid_netcdf4[testfile.nc] - AssertionError: assert 'phony_dim_0' == 'phony_dim_1'
    FAILED h5netcdf/tests/test_h5netcdf.py::test_invalid_netcdf4_mixed[testfile.nc] - AssertionError: assert 'y1' == 'z1'

Any idea what's up with these?  

Tried again with h5py 2.8.0 and got the same result.  Strange, as it looks like the travis tests are passing.

**Comment by shoyer** [comment]
What version of libnetcdf are you using? If I recall correctly, this requires a relatively recent bug-fix to libnetcdf.

**Comment by kmuehlbauer** [comment]
@jready This is implemented in netcdf-c [4.7.3](https://github.com/Unidata/netcdf-c/releases/tag/v4.7.3) and available in `h5netcdf=0.8.0`. Please reopen if still an issue.
