### ISSUE TITLE
h5py3 string encoding issues with xarray

### ISSUE THREAD

**Issue by kmuehlbauer** [h5netcdf/h5netcdf#84]
While testing `xarray` with the new string encoding introduced in #82 I found that the current string_check is not sufficient and will result in unwanted decoding of data 

Currently the check is as follows:

https://github.com/h5netcdf/h5netcdf/blob/2bf46a7728ff8fcf96374a882d2272d17595e311/h5netcdf/core.py#L153-L155

This is a more specific test which only wraps strings with length=None with `.asstr()`.

```python
        if getattr(self._root, "decode_strings", False):
            string_info = h5py.check_string_dtype(self._h5ds.dtype)
            if string_info and string_info.length is None:
                return self._h5ds.asstr()[key]
```
While doing this I've found some more minor glitches (which are more or less style issue).

I've created two notebooks comparing current and proposed status https://gist.github.com/kmuehlbauer/f5b1c94b146d7041563527be0c0c84a6.

@shoyer I'll link a PR soon.

**Comment by kmuehlbauer** [comment]
I've removed the `bug` - label since this might not actually be a bug in that sense, but some kind of interoperability issue.

**Comment by kmuehlbauer** [comment]
This is a nice read of string handling in netcdf4-python https://unidata.github.io/netcdf4-python/#dealing-with-strings. And here similar for h5py https://docs.h5py.org/en/stable/strings.html and https://docs.h5py.org/en/stable/special.html

`xarray` uses `set_auto_chartostring(False)` to disable automatic conversion from char arrays to strings:

```python
    def get_array(self, needs_lock=True):
        ds = self.datastore._acquire(needs_lock)
        variable = ds.variables[self.variable_name]
        variable.set_auto_maskandscale(False)
        # only added in netCDF4-python v1.2.8
        with suppress(AttributeError):
            variable.set_auto_chartostring(False)
        return variable
```

@shoyer I think the current state of #85 is doing pretty much the same as `set_auto_chartostring` above. (This would still need some improvement.)

Let's take this h5dump (which is created via a numpy bytes array):

```
DATASET "bytes_var" {
      DATATYPE  H5T_STRING {
         STRSIZE 1;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SIMPLE { ( 6 ) / ( 6 ) }
      DATA {
      (0): "f", "o", "o", "b", "a", "r"
      }
      ATTRIBUTE "DIMENSION_LIST" {
         DATATYPE  H5T_VLEN { H5T_REFERENCE { H5T_STD_REF_OBJECT }}
         DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
         DATA {
         (0): (DATASET 331 /string6 )
         }
      }
   }
```

`netcdf4-python` uses numpy arrays  with `dtype='S'` to represent this string, so the above will result in `array(b'foobar', dtype='|S6')` (and this is also what `xarray` does). `h5py` using the `asstr()` wrapper yields `array(['f', 'o', 'o', 'b', 'a', 'r'], dtype=object)` and without wrapping `array([b'f', b'o', b'o', b'b', b'a', b'r'], dtype='|S1')`. So this does not yield the wanted/needed representation in either way. To be honest, this might not be a problem for `h5netcdf`, but a huge one for downstream packages like `xarray`.

@shoyer If you have a suggestions what and where should be done to resolve this please share your thoughts.

**Comment by kmuehlbauer** [comment]
OK, I've something probably useful setup over in https://github.com/pydata/xarray/pull/4893.

**Comment by shoyer** [comment]
Thanks for looking in this.

I think your fix in https://github.com/h5netcdf/h5netcdf/pull/85 is on the right track. For consistency with netCDF4-Python, we probably do only want to automatically decode vlen str arrays automatically, not fixed width ascii.

In the long term, we might end up wanting our own `asstr()` method if we care about full compatibility with h5py.

**Comment by shoyer** [comment]
I just made a 0.10.0 release, and pushed it to both pypi and github.

**Comment by kmuehlbauer** [comment]
Thanks @shoyer, that's great.
