### ISSUE TITLE
Storing python dictionaries

### ISSUE THREAD

**Issue by peendebak** [h5netcdf/h5netcdf#86]
Is it possible to store (nested) python dictionaries with netcdf4? The following minimal example I tried raises an exception.

```
import h5netcdf
import numpy as np
import tempfile

with h5netcdf.File(tempfile.mktemp(suffix='.nc'), 'w') as f:
    f.dimensions = {'x': 5}

    v = f.create_variable('hello', ('x',), float)
    v[:] = np.ones(5)

    v = f.create_variable('/grouped/data', ('y',), data=np.arange(10))

    v.attrs['foo'] = 'bar' # works
    v.attrs['dict'] = {'a': 1, 'b': {'c': 0}} # fails
```
If storing dictionaries is not yet possible, what would it require to implement this inside h5netcdf?

Running:
Python version 3.8
h5netcdf version 0.10.0.
h5py version 2.10.0

The full traceback for the exception is:
```
Traceback (most recent call last):

  File "<ipython-input-1-64012b7c12b6>", line 14, in <module>
    v.attrs['dict'] = {'a': 1, 'b': {'c': 0}} # fails

  File "c:\projects\py38\lib\site-packages\h5netcdf\attrs.py", line 37, in __setitem__
    self._h5attrs[key] = value

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "c:\projects\py38\lib\site-packages\h5py\_hl\attrs.py", line 100, in __setitem__
    self.create(name, data=value)

  File "c:\projects\py38\lib\site-packages\h5py\_hl\attrs.py", line 184, in create
    htype = h5t.py_create(original_dtype, logical=True)

  File "h5py\h5t.pyx", line 1634, in h5py.h5t.py_create

  File "h5py\h5t.pyx", line 1656, in h5py.h5t.py_create

  File "h5py\h5t.pyx", line 1711, in h5py.h5t.py_create

TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

**Comment by kmuehlbauer** [comment]
@peendebak Thanks for raising this. Could you please add the full traceback and the hdf5 version for completeness?

**Comment by peendebak** [comment]
@kmuehlbauer I added the information the first comment

**Comment by kmuehlbauer** [comment]
Although I've never seen any python dictionary directly read or written to `netcdf` or `hdf5` attributes, it doesn't mean it won't exist. But also the documentation over at `NetCDF` [1] states that _"Attributes are all either scalars (single-valued) or vectors (a single, fixed dimension)"_ [2].

You can still solve this by storing the key,value-pairs via `groups` (hdf5/netcdf4), but this would involve a specific reader/writer function on your side to correctly pack/unpack your dictionary. Examples are on SO for hdf5 [3][4] which could be adapted to `netcdf4` or `h5netcdf`.

[1] https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_data_set_components.html
[2] https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_data_set_components.html#attributes) 
[3] https://stackoverflow.com/a/62470570
[4] https://stackoverflow.com/a/61262342

**Comment by kmuehlbauer** [comment]
@peendebak Did you get along with your problem here? Please let us know, so we can close the issue.

**Comment by shoyer** [comment]
Unfortunately I don't think HDF5 has any analogous data types to a Python dictionary.

You would need to use your own encoding convention of sort of some, e.g., perhaps saving the data as a JSON string. If you like, you could even put it in an opaque data type: https://docs.h5py.org/en/stable/special.html#storing-other-types-as-opaque-data.

The downside of these custom approaches is that the data will only be readable by your own application, not generic HDF5/netCDF tools.

**Comment by kmuehlbauer** [comment]
I'm closing this as `wontfix`. Several approaches how to save python dictionaries hdf5 files have been proposed.
