### ISSUE TITLE
h5pyd testing

### ISSUE THREAD

**Issue by kmuehlbauer** [h5netcdf/h5netcdf#89]
In #87 re-adding of `h5pyd`-testing was discussed. 

The two obvious possibilities are:

- an `h5pyd` endpoint controlled by https://github.com/h5netcdf/h5netcdf
- CI based `h5pyd`-serving while testing

**Comment by kmuehlbauer** [comment]
So after reading several resources on that I think I get the message of @ajelenak's [comment](https://github.com/h5netcdf/h5netcdf/pull/87#issuecomment-808260731): _This turned to be a pain the first time._

As we can't use `h5serv` due to lack of dimension scale support we would need to use `hsds`. Over at https://github.com/HDFGroup/h5pyd this is used via docker directly in the testsuite. A possible approach here too, @ajelenak?

**Comment by ajelenak** [comment]
What a coincidence... Just yesterday I was in a meeting where the same approach you mentioned was recommended. I can try that approach in a couple of weeks.

**Comment by kmuehlbauer** [comment]
@ajelenak That would be great.

**Comment by jreadey** [comment]
HSDS/h5pyd now supports a direct access mode (see: https://github.com/HDFGroup/hsds/blob/master/docs/design/direct_access/direct_access.md) where h5pyd instantiates the hsds functionality as sub-processes.  This means no docker needed, no secure passwords, or tcp connections.  Should make it much easier for ci test enviroments.

**Comment by kmuehlbauer** [comment]
@jreadey Thanks for that great news. Is this already used somewhere else, so that we might get some idea of usage?

**Comment by jreadey** [comment]
It's beta level now, but should be solid enough for h5netcdf testing.  @ajelenak or I should be able to submit a PR soon with the needed changes.

**Comment by ajelenak** [comment]
A PR that brings back h5pyd testing is in #162. It kicks in only if both h5pyd and hsds packages are available so it will not disrupt the current h5netcdf testing.
