### ISSUE TITLE
Improve FutureWarning: String decoding changed with h5py >= 3.0.

### ISSUE THREAD

**Issue by paugier** [h5netcdf/h5netcdf#90]
I get many warnings like this one:

```
  /home/pierre/.pyenv/versions/3.8.2/lib/python3.8/site-packages/h5netcdf/core.py:765: FutureWarning: String decoding changed with h5py >= 3.0. Currently backwards compatibility with h5py < 3.0 is kept by decoding vlen strings per default. This will change in future versions for consistency with h5py >= 3.0. Setting 'decode_vlen_strings=True' forces string decoding.
    warnings.warn(msg, FutureWarning, stacklevel=0)
```

It seems to me that this warning could be improved. I don't know what I should do with it and how I should modify my code.

1. I guess some users (as me) don't understand what are "vlen strings". 
2. I don't know how and where I should change my code (the given line h5netcdf/core.py:765 is not useful for a user).
3. I get this warning with  h5py-3.2.1 and I don't mind about supporting h5py < 3.0.

I think an example of good warning message is

```
  /home/pierre/Dev/pythran/pythran/types/conversion.py:10: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    numpy.int: 'npy_int',
```
The warning is emitted by Numpy but it shows exactly where is the problem (here, in Pythran). There is an good explanation (with a link) and it explains what has to be done to fix the issue. It would be great to improve the FutureWarning to get something as good! I guess it may not be as easy!

Just changing to `warnings.warn(msg, FutureWarning, stacklevel=2)` is already better since it points to the correct line in the code (where `h5netcdf.File` is used).

**Comment by kmuehlbauer** [comment]
@paugier Thanks for raising this. The warning message can indeed be a bit more clear.

Currently, `h5netcdf.File()` is invoked with `decode_vlen_strings=True`. If you want compatibility with h5py>=3.0 then you would need to invoke `h5netcdf.File` with kwarg `decode_vlen_strings=False`. This would also silence the warning. In a later version this will be the default behaviour, hence the warning.

**Comment by kmuehlbauer** [comment]
@paugier Would this work better from user-perspective:

```
                if self.decode_vlen_strings is None:
                    msg = (
                        "String decoding changed with h5py >= 3.0. "
                        "See https://docs.h5py.org/en/latest/strings.html for more details. "
                        "Currently backwards compatibility with h5py < 3.0 is kept by "
                        "decoding vlen strings per default. This will change in future "
                        "versions for consistency with h5py >= 3.0. To silence this "
                        "warning set kwarg ``decode_vlen_strings=False``. Setting "
                        "``decode_vlen_strings=True`` forces string decoding."
                    )
                    warnings.warn(msg, FutureWarning, stacklevel=2)
```

@shoyer How should we go about this? Would this fit into some 0.10.1 version?

**Comment by shoyer** [comment]
Sure, if you submit a patch I can tag and upload to pypi. Or better yet I could add you as a maintainer on pypi :)

**Comment by kmuehlbauer** [comment]
> Or better yet I could add you as a maintainer on pypi :)

Sounds like a plan, my user is the same on pypi as here on github. Would be nice to completely automate releases. I'll open another issue for that.

**Comment by paugier** [comment]
Thank you for your replies. I was wondering if it could make sense to provide an API to globally switch the behavior to what we'll get in future?

**Comment by kmuehlbauer** [comment]
@paugier Do you think something along the lines of `set_options` (eg. in `xarray`) would work?
