### ISSUE TITLE
Collaboration Guidelines

### ISSUE THREAD

**Issue by kmuehlbauer** [h5netcdf/h5netcdf#96]
`h5netcdf` is not only a vital part of `xarray` backends but also widely used in data science packages [1]. 

As we've seen in the past month's changes in dependencies, new features, multiple bug fixes require maintainer/collaborator attention to the package. Currently there is not that much of a backlog, but this might increase in the future. As `h5netcdf` is a crucial part of workflows in my field (weather radar), it's very much in my interest to keep `h5netcdf` in a healthy state. Thanks again @shoyer for warmly welcoming me as an `h5netcdf` collaborator and maintainer.

GitHub allows us to fine tune almost everything to make workflows as collaborator and maintainer friendly as possible. So I would just add some points which could be introduced to `h5netcdf` to foster collaboration, maintenance and visibility:

- [x] write down collaboration guidelines (either in wiki or in dedicated documentation)
- [x] setup branch protection rules (better safe than sorry ;-))
  - requiring approving reviews, enabled in branch protection rules
  - requiring status check passes, enabled in branch protection rules
  - requiring branches to be up to date, enabled in branch protection rules
- [x] require changelog updates per each Pull Request
- [x] use linear history (like `xarray`, squash-merges) enabled in branch protection rules
- [x] how to handle self merges
- [x] release workflow guidelines (steps needed for a release) https://github.com/h5netcdf/h5netcdf/wiki#release-workflow
- [x] issue / pull request templates (#114)
- [x] dedicated documentation (mostly now in the README.rst, but also API docs would be nice)
- tbc

There might be points which do not need immediate action. Thanks for any feedback.

I'll start creating a wiki page describing the release workflow.

[1] https://github.com/h5netcdf/h5netcdf/network/dependents

**Comment by shoyer** [comment]
This sounds like a great plan to me! These would all be welcome improvements.

**Comment by kmuehlbauer** [comment]
@shoyer I've added a section to the wiki `Contribution Guidelines`. These reflect my opinion. I'm very much open for changes and additions.

**Comment by kmuehlbauer** [comment]
All point raised above have been tackled by now so this can be closed. :tada:
